#
# Makefile for Elecard 7105-based boards
#

obj-y += setup.o
obj-y += setup_pci.o
obj-y += setup_stb830.o
obj-y += setup_stb840_promSvyaz.o
obj-y += setup_stb840_promWad.o
obj-y += setup_stb840_ch7162.o

