#!/bin/sh
#

case "$1" in
	start)

		echo "/sbin/mdev" > /proc/sys/kernel/hotplug
		if [ -f /etc/dev.tar ]; then
			# Using prebuilt /dev/ archive in retail mode
			echo -n "Populating /dev using /etc/dev.tar..."
			cd /dev
			tar -xf /etc/dev.tar
			[ -f /etc/dev-stapi.tar ] && tar -xf /etc/dev-stapi.tar 
		else
			# Using mdev, mdev -s already should be started into initramfs
			mkdir -p /dev/pts /dev/shm /dev/mqueue
			ln -s /proc/self/fd /dev/fd
		fi
		echo "/usr/sbin/modprobe" > /proc/sys/kernel/modprobe

		echo "done"
		;;
	*)
		echo $"Usage: $0 {start}"
		exit 1
esac

