#!/bin/sh
#

USB_DEVICES=/sys/bus/usb/devices

case "$1" in
	start)
		grep usbfs /proc/mounts &>/dev/null || mount -t usbfs none /proc/bus/usb
		#scan usb devices
		for usbDevDir in `ls $USB_DEVICES | grep -Ev ":|usb"`; do
			VID=`cat $USB_DEVICES/$usbDevDir/idVendor`
			PID=`cat $USB_DEVICES/$usbDevDir/idProduct`
			#search usb modems for software reboot it
			if [ -f "/usr/share/usb_modeswitch/${VID}:${PID}" ]; then
				#Drop configure value for device, and then restore it. This almost the same as reset.
				prevConfigure=`cat $USB_DEVICES/$usbDevDir/bConfigurationValue`
				echo "0" >$USB_DEVICES/$usbDevDir/bConfigurationValue
				echo "$prevConfigure" >$USB_DEVICES/$usbDevDir/bConfigurationValue
			fi
		done
		;;
	*)
		echo $"Usage: $0 {start}"
		exit 1
esac
