#!/bin/sh
#
# Start install modules....
#

BOARD_NAME=${board_name%.*}

case "$1" in
	start)
		if [ "$BOARD_NAME" = "stb850" ]; then
			modprobe em28xx
			#disable sd/mmc
			echo 0 >/sys/bus/usb/devices/1-1.3/bConfigurationValue &
		fi
		;;
	stop)
		if [ "$BOARD_NAME" = "stb850" ]; then
			modprobe -r em28xx
		fi
		;;
	restart|reload)
		"$0" stop
		"$0" start
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?

