#!/bin/sh
#
# Start the network....
#

export PATH=$PATH:/opt/elecard/bin

if [ `edcfg /var/etc/ifcfg-wlan0 get WAN_MODE` = "1" ]; then
WAN=wlan0
LAN=eth0
else
WAN=eth0
LAN=wlan0
fi

case "$1" in
  start)
	echo -n "Starting network... "

	modprobe rt2800usb &> /dev/null

    if [ -d /sys/class/net/eth1 ]; then
	LAN=br0
	brctl addbr br0
	brctl setfd br0 0
    fi
	if ! grep /dev/nfs /proc/cmdline > /dev/null; then
[% IF ! CONFIG_TESTSERVER_ENABLE -%]
		/sbin/ifup -a
[% END -%]
		:
	else
		# Get routes and nameservers from dhcp
		udhcpc -n -i eth0 -s /opt/elecard/bin/udhcpc.nfs
		test -d /sys/class/net/wlan0 && ifup wlan0
	fi

	if brctl show | grep $WAN >/dev/null; then
		IPTV_GW=$LAN
	else
		IPTV_GW=$WAN
	fi
	route add -net 224.0.0.0 netmask 240.0.0.0 $IPTV_GW

[% IF ENV.UPD_CONFIG != "rel" -%]
	echo -n "telnet "
	telnetd
[% END -%]

	if [ -d /sys/class/net/wlan0 -o -d /sys/class/net/eth1 ] && \
	   [ "`edcfg /var/etc/ifcfg-lan get MODE`" = "NAT" ]; then
		echo -n "dhcpd "
		touch /var/etc/dhcpd.leases
		[ -f /var/etc/dhcpd.conf ] || ifcfg dhcp > /var/etc/dhcpd.conf
		dhcpd -q -lf /var/etc/dhcpd.leases -cf /var/etc/dhcpd.conf $LAN
	fi

	if ! brctl show | grep $WAN > /dev/null; then
		# Enable ip forwarding
		echo 1 > /proc/sys/net/ipv4/ip_forward
	fi
	echo "done"

	;;
  stop)
	echo -n "Stopping network... "
	killall telnetd
	killall dhcpd
	killall udhcpc
	iptables -t nat -F
	echo 0 > /proc/sys/net/ipv4/ip_forward
	if [ -z "`cat /proc/cmdline | grep /dev/nfs`" ]; then
		ifdown -a
	else
		ifdown $LAN
	fi
	test -d /sys/class/net/wlan0 && ifdown wlan0
	brctl delbr br0 2>/dev/null
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
