#!/bin/sh
#
# Start stb830 keyscanner
#
[% SKIPFILE %]
#This already not used, because for stb830 keyscanner changed on ct1628 chip

BOARD_NAME=${board_name%.*}

case "$1" in
	start)
		if [ "$BOARD_NAME" = "stb830_st" ]; then
			echo "Starting keyscanner... "
			modprobe keyscanner
			if [ ! -c /dev/keypad ]; then
				mknod /dev/keypad c 99 0
			fi
		fi
# ct1628 driver build in kernel now.
		;;
	stop)
		rmmod keyscanner
		;;
	restart|reload)
		"$0" stop
		"$0" start
		;;
	*)
		echo $"Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?

