#!/bin/sh
#
# Start/stop watchdog.
#
[% SKIPFILE %]
ls -la /dev/watchdog
exit 0
case "$1" in
	start)
		echo -n "Starting watchdog..."
		watchdog -t 10 -T 20 /dev/watchdog
		echo "done."
		;;
	stop)
		echo -n "Stopping watchdog..."
		killall watchdog
		echo "done."
		;;
	*)
		echo $"Usage: $0 {start|stop}"
		exit 1
esac

exit 0
