#!/bin/sh
#
# Start Elecard daemon
#
# if defined testServer or testTool, this starts in /etc/inittab
#

[% IF ! CONFIG_ELECD_ENABLE -%]
  [% SKIPFILE %]
[% END -%]


STAPISDK_ROOT=/root
#STAPISDK_ROOT=/root_33.1
APP=main_sdk7105_7105_ST40_LINUX_32BITS.out
APP_PATH=$STAPISDK_ROOT/$APP
APP_PVR=StbPvr
#URL=udp://234.5.5.10:1239


case "$1" in
  start)
    if ! grep /dev/nfs /proc/cmdline &>/dev/null; then
      . /etc/profile
      echo $APP_PATH $URL
[% IF (ENV.ELCD_USE_LIBIOCTL == 1) -%]
      LD_PRELOAD=/serga/libictl/register_frame_info_fix.so:/opt/elecard/lib/libioctl.so $APP_PATH $URL
[% ELSE -%]
      $APP_PATH $URL
[% END -%]
      while [ ! -e /tmp/elcd.sock ]; do
        usleep 100000
      done
[% IF (ENV.ENABLE_PVR == 1) -%]
      $APP_PVR >>/var/log/StbPvr.log 2>&1 &
[% END -%]
      mainapp.sh &
    fi

    ;;
  stop)
    killall $APP
    echo "done."
    ;;
    restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
