#!/bin/sh
#
# Start updater daemon....
#
export PATH=$PATH:/opt/elecard/bin

case "$1" in
   start)
#	ntpdate 192.168.1.2 
	updaterDaemon &
	;;
   stop)
	killall updaterDaemon
	;;
   restart|reload)
	"$0" stop
	"$0" start
	;;
   *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
