#!/bin/sh

KERNEL_VERSION=linux-sh4-2.6.32.42_stm24_V4.0
KERNEL_DIR_PREV=/opt/STM/STLinux-2.4/devkit/sources/kernel/$KERNEL_VERSION
KERNEL_DIR_PACKAGES=$BUILDROOT/packages/$KERNEL_VERSION
if [ -e $KERNEL_DIR_PREV -a ! -e $KERNEL_DIR_PACKAGES ]; then
	ln -s $KERNEL_DIR_PREV $KERNEL_DIR_PACKAGES
	touch $KERNEL_DIR_PACKAGES/.ts_unpacklinux
fi

STAPISDK_VERSION=stapisdk-35.1
STAPISDK_DIR_PREV=/opt/STM/$STAPISDK_VERSION
STAPISDK_DIR_PACKAGES=$BUILDROOT/packages/$STAPISDK_VERSION
if [ -e $STAPISDK_DIR_PREV -a ! -e $STAPISDK_DIR_PACKAGES ]; then
	ln -s $STAPISDK_DIR_PREV $STAPISDK_DIR_PACKAGES
	touch $STAPISDK_DIR_PACKAGES/.unpackstapisdk
fi

MULTICOM_VERSION=multicom-4.0.5
MULTICOM_DIR_PREV=/opt/STM/MULTICOM/$MULTICOM_VERSION
MULTICOM_DIR_PACKAGES=$BUILDROOT/packages/$MULTICOM_VERSION
if [ -e $MULTICOM_DIR_PREV -a ! -e $MULTICOM_DIR_PACKAGES ]; then
	ln -s $MULTICOM_DIR_PREV $MULTICOM_DIR_PACKAGES
fi
