#!/bin/sh

#Comment that add to firmware pack name
SHORT_COMMENT=${SHORT_COMMENT:-$1}

export UPD_CONFIG ENABLE_VIDIMAX BUILD_SCRIPT_FW BUILD_WITHOUT_COMPONENTS_FW BUILD_SIGN_WITH BUILD_ADD_KEYS_TO_FW SHORT_COMMENT

make -C $PRJROOT firmware
