#!/bin/sh


# Start/stop all init scripts in /etc/init.d
# executing them in numerical order.
#
LIST=
if [ "$1" = "start" ]; then
	LIST=`ls /etc/init.d/S??*`
else if [ "$1" = "stop" ]; then
	LIST=`ls -r /etc/init.d/S??*`
else
	exit 1
fi
fi

for i in $LIST;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set $1
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i $1
	    ;;
    esac
done

