#!/bin/sh

standbyoff()
{
	StbCommandClient -f /tmp/frontpanel 'delays 500 200'
	StbCommandClient -f /tmp/frontpanel 'notify 5 STAND UP'
	StbCommandClient -f /tmp/elcd.sock  '{"method":"standby","params":[true],"id": 1}'
}

standbyon()
{
	StbCommandClient -f /tmp/frontpanel 'delays 500 200'
	StbCommandClient -f /tmp/frontpanel 'notify 5 SLEEP'
	StbCommandClient -f /tmp/elcd.sock  '{"method":"standby","params":[],"id": 1}'
#	StbCommandClient -f /tmp/frontpanel 'time 1'
}

if [ `basename $0` = "standbyoff" ]; then
	standbyoff
else
	standbyon
fi
